# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Configuration for pip
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
# for reference:
#     ignore:
#       # Ignore updates to packages that start with 'aws'
#       # Wildcards match zero or more arbitrary characters
#       - dependency-name: "aws*"
#       # Ignore some updates to the 'express' package
#       - dependency-name: "express"
#         # Ignore only new versions for 4.x and 5.x
#         versions: ["4.x", "5.x"]
  # Configuration for github-actions
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
